### ISSUE TITLE
Rendre responsive + conformité designs

### ISSUE THREAD

**Issue by augnustin** [betagouv/pass-culture-browser#103]
Refaire une passe sur indesign

**Comment by arnoo** [comment]
Ce que je vois notamment: 
- Les boutons ont changé (au moins gauche, droite et "flip" sur l'écran principal)
- Mise en page du "deck": Ion a maquetté plusieurs tailles d'écran. De mémoire, l'idée est que la zone d'image (gradient inclus) fasse 4/3. Le deck s'adapte. Si on a pas la place pour avoir un deck décent en 4/3, il faut réduire le ratio  de la zone image en coupant en haut et en bas de cette zone (la zone image doit donc être centrée verticalement dans un conteneur en overflow hidden...)

**Comment by augnustin** [comment]
@arnoo @Ledoux vous avez une idée des tailles d'écrans que l'on souhaite couvrir ? Genre une largeur et une longueur min/max ?
