### ISSUE TITLE
Scroll vers le haut pour activer verso ne marche pas ?

### ISSUE THREAD

**Issue by Ledoux** [betagouv/pass-culture-browser#121]

**Comment by augnustin** [comment]
C'est pas que sur IOS, juste c'est pas encore codé. A voir si je merge la branche #42 ou si on refait qqch de nouveau.

**Comment by augnustin** [comment]
Est-ce que ça fonctionne maintenant ?

**Comment by Ledoux** [comment]
@augnustin 
alors pas trop encore,
comme on a cette histoire de board avec les boutons qui genent pour faire un drag dessus, c'est pas facile.

**Comment by augnustin** [comment]
Ah car on veut pouvoir dragguer au dessus des boutons ? Effectivement cela s'annonce compliqué ...
