### ISSUE TITLE
[Chrome-ios] Status Bar mange le menu et c'est pas beau de scroller pour afficher le bouton connexion

### ISSUE THREAD

**Issue by Ledoux** [betagouv/pass-culture-browser#122]

**Comment by arnoo** [comment]
Attention pour le bouton connexion : on ne peut pas faire d'overflow scroll ou auto sur autre chose que la div principale pour avoir le bouton toujours pile en bas. Sinon, ça foire quand on ouvre le clavier virtuel sur les mobiles (ce qui fait un redimensionnement de la fenêtre),  min-height 100% est OK par contre.
