### ISSUE TITLE
iOS webapp : cacher l'interface de Safari

### ISSUE THREAD

**Issue by IonLzr** [betagouv/pass-culture-browser#154]
Masquer les barres de commandes hautes et basses de Safari lorsqu'on consulte le site après l'avoir "ajouté à l'écran d'accueil"

(au cas où : https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html#//apple_ref/doc/uid/TP40002051-CH3-SW2 )

**Comment by arnoo** [comment]
Il doit y avoir une astuce quelque part, parce j'avais déjà mis le tag "apple-mobile-app-capable" depuis longtemps dans public/index.htm...

**Comment by IonLzr** [comment]
Peut-être une confusion dans les versions de ma part… Dans tous les cas, ça fonctionne.
