### ISSUE TITLE
firstThumbDominantColor trop claire 

### ISSUE THREAD

**Issue by IonLzr** [betagouv/pass-culture-browser#159]
Ex. : https://app.passculture-staging.beta.gouv.fr/decouverte/XA/A4 
Ici, le rgb(77, 57, 0) a une luminosité de 30% au lieu des 15% attendus.
Edit:  idem ici, luminosité à 30% pour le rgb(0, 36, 77) : https://app.passculture-staging.beta.gouv.fr/decouverte/tuto/A9

**Comment by arnoo** [comment]
Le 15% correspondait au V d'un HSV ou B d'un HSB. Il faut diviser par 2 pour avoir le L d'un HSL
