### ISSUE TITLE
Espacer les points sur les filets de séparation en pointillés

### ISSUE THREAD

**Issue by IonLzr** [betagouv/pass-culture-browser#160]
Soit en utilisant l'asset fourni (essais de rendu nécessaires), soit peut-être avec l'une des méthodes  discutées ici : https://stackoverflow.com/questions/6250394/how-to-increase-space-between-dotted-border-dots
La maquette utilise une ligne alternant 1px coloré avec 4 px d'espace.

**Comment by augnustin** [comment]
J'ai opté pour la solution stackoverflow. :-)

**Comment by giuseppebergman** [comment]
La classe.
