### ISSUE TITLE
OfferInfo/Quand : trouver une meilleure presentation quand il y a beaucoup de dates

### ISSUE THREAD

**Issue by arnoo** [betagouv/pass-culture-browser#171]
+ retirer la limite à 7 dates qui est la juste pour la demo

**Comment by augnustin** [comment]
La première option à laquelle je pense c'est d'afficher directement le calendrier en read-only.

Mais laissons @IonLzr nous suggérer quelque chose !

**Comment by IonLzr** [comment]
Voici une maquettes présentant trois cas de figure pour la date : des commentaires explicatifs sont dispo sur invision.
https://octo.invisionapp.com/d/main#/console/13620708/296647336/preview#project_console
