### ISSUE TITLE
Chrome / desktop : Mes Résas - visuels pas en 4/3 déformés

### ISSUE THREAD

**Issue by IonLzr** [betagouv/pass-culture-browser#197]
J'ai essayé un `background-size: cover;` sans succès.
<img width="543" alt="capture d ecran 2018-04-17 a 19h43 16" src="https://user-images.githubusercontent.com/37805352/38887842-3c9ef506-427a-11e8-9b60-0deba78ed882.png">

**Comment by augnustin** [comment]
Pas loin ! C'était `object-fit: cover;` :smile:

**Comment by IonLzr** [comment]
Cool !

**Comment by IonLzr** [comment]
Cool, merci !
