### ISSUE TITLE
Petit glitch blanc quand on flip le verso 

### ISSUE THREAD

**Issue by Ledoux** [betagouv/pass-culture-browser#202]
![caps](https://user-images.githubusercontent.com/3239692/38931897-f081c3ec-4314-11e8-954a-3b6c6093ba20.gif)

**Comment by Ledoux** [comment]
ca se voit quasiment pas sur le gif...

**Comment by augnustin** [comment]
Pour fixer cela, il fallait que le verso soit juste en dessous du recto : 

![image](https://user-images.githubusercontent.com/1970156/38936711-adc1575e-4321-11e8-8939-cedee8f6dfb3.png)
![image](https://user-images.githubusercontent.com/1970156/38936723-b496ecd8-4321-11e8-9289-e88b448be32a.png)


Le soucis c'est que le petit triangle du type d'offre dépasse. aussi, j'ai dû remonter un peu la zone de contrôle, le point à partir duquel commence le gradient et agrandir un peu l'image. 

Les autres solutions possibles étaient:
- masquer le triangle tant qu'on n'est pas flipped (bizarre qu'il apparaisse après)
- mettre un fond de la couleur du triangle, mais du coup ça fait que le triangle émerge c'était un peu bizarre
- jouer avec le triangle. Ex: lui faire contenir le bouton 'to-verso' mais cela changeait pas mal le design.

@IonLzr qu'en penses-tu ?

**Comment by IonLzr** [comment]
Si je te suis bien : 
> masquer le triangle tant qu'on n'est pas flipped (bizarre qu'il apparaisse après)

S'il est masqué mais s'affiche dès que l'on tap, ça devrait être imperceptible, non ?
Et ça permettrait d'éviter d'avoir à remonter la zone de contrôle, pour garder une souplesse dans le placement sur les devices très hauts.

**Comment by Ledoux** [comment]
![caps](https://user-images.githubusercontent.com/3239692/38941116-20354548-432c-11e8-9de6-e1659e9ca8e4.gif)
