### ISSUE TITLE
calendrier pas centré et on ne voit pas tres bien les dates selectionnables

### ISSUE THREAD

**Issue by Ledoux** [betagouv/pass-culture-browser#203]
<img width="453" alt="screen shot 2018-04-18 at 14 33 19" src="https://user-images.githubusercontent.com/3239692/38932080-7b2a8cd6-4315-11e8-9101-4987886ddc08.png">

**Comment by Ledoux** [comment]
<img width="251" alt="screen shot 2018-04-18 at 14 34 38" src="https://user-images.githubusercontent.com/3239692/38932142-a6cf856c-4315-11e8-93f7-ee4d0a55db5f.png">

**Comment by augnustin** [comment]
Quel device ?
Chez moi ça donne:

![image](https://user-images.githubusercontent.com/1970156/38932807-8bd2f8aa-4317-11e8-910f-057d09fabefd.png)

**Comment by Ledoux** [comment]
sur chrome web

**Comment by augnustin** [comment]
Étonnamment le problème du centrage est très compliqué et devra faire l'objet d'une PR sur `react-dates`. Je m'y attelle de ce pas...
