### ISSUE TITLE
Terminé sur les cartes tuto

### ISSUE THREAD

**Issue by Ledoux** [betagouv/pass-culture-browser#223]

**Comment by augnustin** [comment]
Ah bon ? Moi non : 

![image](https://user-images.githubusercontent.com/1970156/39298309-1fff0706-4946-11e8-8af6-265f018b187a.png)

![image](https://user-images.githubusercontent.com/1970156/39298335-2dab31fe-4946-11e8-8011-726e9bcb664a.png)

Mais je suis ptet pas à jour avec mon backend...

**Comment by Ledoux** [comment]
@augnustin 
fixé de manière hard avec isTuto false... 
on verra si on est reconfronté plus tard
