### ISSUE TITLE
Bouton "voir plus"

### ISSUE THREAD

**Issue by arnoo** [betagouv/pass-culture-browser#233]
Sur la description au verso, avoir la possibilité d'avoir un texte court, et un bouton voir plus pour voir le texte long.

**Comment by augnustin** [comment]
Est-ce qu'on veut demander 2 types de descriptions (une courte et une longue) et on peut afficher la longue en faisant voir plus, ou est-ce qu'on coupe automatiquement à N caractères et voir plus affiche le reste ?
