### ISSUE TITLE
Verso > design : alléger le détail des horaires et jours dans "Quand ?"

### ISSUE THREAD

**Issue by laurenetaravella** [betagouv/pass-culture-browser#238]
Le détail des différents horaires et dates pourrait apparaître de manière plus succincte : plutôt que d'avoir une liste détaillée on pourrait avoir une présentation du type du "tant au tant" et de "telle heure à telle heure", on peut ensuite accéder au détail lorsqu'on sélectionne son créneau dans la liste déroulante en cliquant sur "réservé".

**Comment by IonLzr** [comment]
Cf. https://octo.invisionapp.com/d/#/console/13620708/296647336/preview pour la nouvelle règle de disposition.

**Comment by IonLzr** [comment]
Doublon avec  #171
