### ISSUE TITLE
On ne peut pas accéder au détail des événements sur smarthphone

### ISSUE THREAD

**Issue by manman3** [betagouv/pass-culture-browser#242]

**Comment by augnustin** [comment]
Même genre de questions : sur quel téléphone est-ce que le problème survient ? 
Que signifie "on ne peut pas accéder au détail" ? Le bouton est inactif ? Le drag vers le haut ne fonctionne pas ?

**Comment by augnustin** [comment]
Il s'agissait du problème de scroll, n'est-ce pas ? Si c'est le cas c'est corrigé depuis.

**Comment by Ledoux** [comment]
yes!
