### ISSUE TITLE
L'application saute au bout de 5 min

### ISSUE THREAD

**Issue by manman3** [betagouv/pass-culture-browser#243]
L'écran du portable devient tout noir et ça revient directement au menu du portable

**Comment by augnustin** [comment]
Bonjour,

Est-il possible d'avoir plus d'infos concernant ce bug qui a l'air assez important.

- Quel device ?
- Est-ce qu'une action en particulier déclenche ce comportement ?

Je soupçonne un problème de mémoire, est-ce que le device en question est plutôt vieux ?

**Comment by arnoo** [comment]
A priori pas reproduit depuis le signalement → je ferme le bug
