### ISSUE TITLE
Automatiser la casse des données d'offre

### ISSUE THREAD

**Issue by IonLzr** [betagouv/pass-culture-browser#245]
Appliquer la casse "Première lettre en capitale, le reste en bas de casse" sur les éléments ci-dessous :

- "Gratuit" et "Offert"
- Type
- Date : jour de la semaine

Et "Première lettre en capitale, le reste inchangé" pour : 
- Nom du lieu
- Adresse : premier mot de chaque ligne (si possible ?)
- Adresse : Commune

**Comment by augnustin** [comment]
Quelques questions en suspends : 

![image](https://user-images.githubusercontent.com/1970156/40055854-b0e3a760-5849-11e8-9b47-1282b5cccd50.png)

- Chansons et romances des deux rives du Rhin => Rhin doit-il être en minuscule ?
- Voix de Stras' => Stras' doit-il être en minuscule ?

Pour l'instant j'ajoute uniquement la majuscule au début quand elle manque.

**Comment by IonLzr** [comment]
> Chansons et romances des deux rives du Rhin => Rhin doit-il être en minuscule ?

Non bien sûr, on ne touche pas au nom de l'offre. 
Je mentionnais le nom du lieu (j'ai édité le descritptif pour clarifier), mais même pour lui, tu soulèves un point problématique ci-dessous.


> Voix de Stras' => Stras' doit-il être en minuscule ?


Effectivement, il peut y avoir un nom de ville dans le lieu, flûte. La règle que je suggérais ne fonctionne donc pas pour le lieu.

Faisons comme tu proposes : 

> Pour l'instant j'ajoute uniquement la majuscule au début quand elle manque.

Je modifie le descriptif de l'issue en ce sens.
