### ISSUE TITLE
Pour ven. 18 mai : intégrer le bandeau "beta"

### ISSUE THREAD

**Issue by IonLzr** [betagouv/pass-culture-browser#250]
Asset dispo ici : https://octo.invisionapp.com/d/main#/console/13620708/289210975/inspect 
À appliquer sur tous les écrans (hélas), au même endroit en position:fixed (en bas à gauche).
Merci !

**Comment by augnustin** [comment]
Done : https://github.com/betagouv/pass-culture-browser/pull/253
