### ISSUE TITLE
Drag vers le bas sur chrome pour fermer le verso fait un refresh de la page

### ISSUE THREAD

**Issue by arnoo** [betagouv/pass-culture-browser#258]

**Comment by augnustin** [comment]
On aurait pu se lancer dans des grands projets de type `preventDefault()`, créer des zones dédiées d'override etc. mais tout cela aurait été très hacky, pour des résultats incertains, à maintenir etc.

D'après SO: https://stackoverflow.com/questions/29008194/disabling-androids-chrome-pull-down-to-refresh-feature 

```
body {
  overscroll-behavior: contain;
}
```

Même si elle n'est compatible que chrome, je pense que ça suffit amplement pour le moment : de toute façon ce bug est un edge-case puisqu'il n'a pas lieu quand on installe l'appli.

N'hésitez pas à rouvrir si ça ne fonctionne pas.
