### ISSUE TITLE
Sur chrome mobile en mode web la hauteur de la page est trop importante

### ISSUE THREAD

**Issue by arnoo** [betagouv/pass-culture-browser#259]
On ne voit pas les boutons en bas.
Et il y a des fois ou quand on scrolle pour afficher les boutons on ne peut quand même pas les cliquer.

**Comment by augnustin** [comment]
https://nicolas-hoizey.com/2015/02/viewport-height-is-taller-than-the-visible-part-of-the-document-in-some-mobile-browsers.html
