### ISSUE TITLE
Trouver une solution pour le pbm de Cookie ou Cache au chargement des offres

### ISSUE THREAD

**Issue by Ledoux** [betagouv/pass-culture-browser#261]
Hypothese:
on a rebooté le serveur, les sessions sont donc perdues et l'utilisateur essayent de s'auth avec un cookie d'une session deprecated.

**Comment by arnoo** [comment]
Il semble que ce soit lié au Dexie et pas au Cookie, mais on ne sait pas pourquoi. → Dexie off pour tout le monde pour l'instant.

**Comment by Ledoux** [comment]
Ca va se transformer en nettoyer l'app du worker dexie.

Et utiliser une librairie de type redux-persist avec local storage

**Comment by Ledoux** [comment]
Done with react-persist!
