### ISSUE TITLE
[A11y] Balises Header (Footer…?) et Main

### ISSUE THREAD

**Issue by IonLzr** [betagouv/pass-culture-browser#305]
Chaque page doit contenir une balise de chaque.
En attente de retour de Romy sur la pertinence et compatibilité de cette règle dans le contexte d'une webapp.

**Comment by augnustin** [comment]
C'est déjà le cas.

**Comment by IonLzr** [comment]
Je propose de laisser ouvert, tant qu'on a pas retrouvé quelle page a suscité cette issue (puisque visiblement l'une ou plusieurs de ces balises manquait quelque part…?)
Non ?
