### ISSUE TITLE
[PRO] Lorsque je veux créer un nouveau compte, le bouton Valider n'est pas actif même si j'ai rempli tous les champs

### ISSUE THREAD

**Issue by annemarie35** [betagouv/pass-culture-browser#322]
<img width="502" alt="capture d ecran 2018-06-08 a 11 30 39" src="https://user-images.githubusercontent.com/7688741/41151032-d6b1a72a-6b0f-11e8-87b5-fc1a508e5bc6.png">

**Comment by annemarie35** [comment]
Bug non reproduit ou corrigé, je ferme l'issue

**Comment by augnustin** [comment]
J'ai corrigé entre temps. Mais j'avais mis un référence à l'issue dans le commit, ça n'a pas l'air d'avoir fonctionné ...

**Comment by annemarie35** [comment]
J'ai peut-être pas vu
