### ISSUE TITLE
Mettre à jour la sélection de dates / prix

### ISSUE THREAD

**Issue by IonLzr** [betagouv/pass-culture-browser#325]
… pour être cohérent avec la possibilité d'avoir plusieurs prix pour une seule offre (événements).

Dans le tunnel : 
https://octo.invisionapp.com/d/main/#/console/13620708/286696554/preview#project_console
https://octo.invisionapp.com/d/main/#/console/13620708/286234327/preview#project_console

**Comment by sixertoy** [comment]
Done et livré en prod le 11/09/2018
