### ISSUE TITLE
[PRO][DESIGN] [SIGNUP PAGE]

### ISSUE THREAD

**Issue by annemarie35** [betagouv/pass-culture-browser#332]
Il y a un lien vers Pass Culture sur l'app mais pas sur Invision.
Est-ce qu'on le garde ou pas ?

**Comment by IonLzr** [comment]
C'est le lien permettant de lire les futures CGU. 
On le désactive s'il n'y a aucune mention légale vers lesquelles renvoyer.

**… et on s'inquiète auprès du 2ème étage de ne pas de CGU à accepter lors de l'ouverture du portail aux pros… ?**

**Comment by annemarie35** [comment]
Ok, merci. Je le désactive donc temporairement.
