### ISSUE TITLE
ajouter un isFlipped in url 

### ISSUE THREAD

**Issue by Ledoux** [betagouv/pass-culture-browser#37]
parce que c'est chiant, même pour le dev, quand il s'agit de travailler sur la carte verso.

Setter directement le isFlipped dans l'url permettrait de travailler en hmr avec la carte toujours retournée

**Comment by Ledoux** [comment]
il me semblait que c'était fait avec la valuer isFlipped dans le state

**Comment by augnustin** [comment]
Ah oui. Ben disons qu'on ne perd pas la valeur lors du hot reloading donc on a résolu notre besoin, sans avoir à l'ajouter dans l'URL ce qui était un peu dirty. :smile: 
Je te laisse closer sauf si tu vois autre chose ?
