### ISSUE TITLE
Rajouter un CONTRIBUTING.md dans chaque submodule git pour commencer à poser les standards de code.

### ISSUE THREAD

**Issue by abel-andre** [betagouv/pass-culture-browser#426]
Pour les standards communs cross-languages ou cross-tech on peut mettre un CONTRIBUTING.md dans le main.

**Comment by sixertoy** [comment]
Si on peut aussi y inscrire la façon d'écrire des messages de commits
Pour ma part j'aime bien le mix FR/EN
- EN car comme pour du code les keywords sont plus courts (rest in peace si on avait un hollandais :D)
- FR car cela nous assure + de clarté et de compréhension en communication équipe, même si rien n'est jamais parfait :)

Pour mes tricks de mon côté j'utilise souvent `git amend` via l'ouverture auto d'un éditeur tiers et donc de fournir un body de commentaires plus précis si besoin

**Comment by Ledoux** [comment]
On centralise tout pour le moment dans pass-culture-main/contributing.md

on verra après si c'ets pertinent de séparer?

**Comment by sixertoy** [comment]
je trouve que c'est bien de centraliser
on pourrait aussi mettre en place un wiki sur le main puisque les wiki sont "clonables"
