### ISSUE TITLE
[API][BUG] Pas de message d'erreurs retournée à la création de compte et erreur 500 si Siren non rempli

### ISSUE THREAD

**Issue by annemarie35** [betagouv/pass-culture-browser#441]
Après avoir créé un compte avec pctest.cafe@btmx.fr et siren 692039514

Quand j'essaye de créér un nouveau compte avec 
- même e-mail 
- même SIREN

le POST sur http://localhost/users/signup renvoie une 400 et {}

cf la #424 (sur le siret d'une venue, s'il est faux, on n'a pas de message d'erreur)

![capture d ecran 2018-07-30 a 10 46 05](https://user-images.githubusercontent.com/7688741/43387195-158d321c-93e6-11e8-97f0-bbc35590e347.png)

**Comment by annemarie35** [comment]
`flask_1     | UNHANDLED ERROR :
flask_1     | Traceback (most recent call last):
flask_1     |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
flask_1     |     rv = self.dispatch_request()
flask_1     |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
flask_1     |     return self.view_functions[rule.endpoint](**req.view_args)
flask_1     |   File "/opt/services/flaskapp/src/routes/users.py", line 165, in signup
flask_1     |     maybe_send_offerer_validation_email(new_user, offerer, user_offerer)
flask_1     |   File "/opt/services/flaskapp/src/utils/mailing.py", line 185, in maybe_send_offerer_validation_email
flask_1     |     + obj.siren)
flask_1     | ValueError: Error getting API entreprise DATA for SIREN : 4465633`

**Comment by g4vroche** [comment]
Non reproduit / déjà corrigé par ailleurs : 

 * Si email déjà utilisé alors un message apparaît sous le champ
![capture d ecran de 2018-08-23 10-39-33](https://user-images.githubusercontent.com/491934/44514658-f9d1ad80-a6c0-11e8-9615-79b7eec5c39d.png)

 * Si SIREN invalide (format) ou n'existe pas, on un message d'erreur en regard du champ
![capture d ecran de 2018-08-23 10-41-46](https://user-images.githubusercontent.com/491934/44514728-2b4a7900-a6c1-11e8-81c2-1504458769f5.png)

 * Si SIREN déjà en base, alors si le compte est créé il y aura une demande de rattachement à la structure.
