### ISSUE TITLE
Ajouter un champ credit photo dans le form Mediation...

### ISSUE THREAD

**Issue by Ledoux** [betagouv/pass-culture-browser#452]
Mais du coup la MediationPage se transforme en form

**Comment by g4vroche** [comment]
2 PR en cours : 
 * PRO : https://github.com/betagouv/pass-culture-pro/pull/93
 * API : https://github.com/betagouv/pass-culture-api/pull/139

Questions :

 * PRO
    * EDIT des mediations ?
    * Refactorisation en Form (convention de nommage)?
    * Layout du champ ? Actuellement en bas de form :

![capture d ecran de 2018-08-23 11-50-42](https://user-images.githubusercontent.com/491934/44518547-d0b61a80-a6ca-11e8-8035-b0cbf72c3c4f.png)



 * API : 
   * Ajout d'une colonne ou utilisation de frontText / backText ?
   * Sanitize de l'input nécessaire (request.form['credit']) ?


 * WEBAPP
   * Affichage du crédit ?
