### ISSUE TITLE
[PRO][BUG] Prendre en compte la validation user_offerer dans les check de permissions

### ISSUE THREAD

**Issue by g4vroche** [betagouv/pass-culture-browser#476]
STR : 
* Créer un compte PRO avec un SIREN déjà en base (et possédant des offers).
  => On est redirigé avec un message signalant que le rattachement va être validé
* Aller sur /offres
* Cliquer sur une offer
* Modifier l'offer
* Sauvegarder

**Comment by arnoo** [comment]
Merci !

Pour les prochaines, tu peux les ajouter directement dans le kanban (en essayant de deviner la priorité, on ajustera après), comme ça on évite que le ticket ne se perde, vu qu'on en a plein d'ouverts.

Hugues Charleux <notifications@github.com> writes:

> STR :
>
> * Créer un compte PRO avec un SIREN déjà en base (et possédant des offers).
>  => On est redirigé avec un message signalant que le rattachement va être validé
> * Aller sur /offres
> * Cliquer sur une offer
> * Modifier l'offer
> * Sauvegarder
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.


-- 
Arnaud Bétrémieux
Consultant
OCTO Technology
.....................
34, Avenue de l'Opéra
75002 Paris
+33 (0)6 89 85 88 41
du lundi au jeudi
http://www.octo.com/
http://blog.octo.com/

**Comment by abel-andre** [comment]
En fait on a 2 soucis de check de permission dans la fonction `ensure_current_user_has_rights(RightsType.editor, offererId)`:
- on ne vérifie pas que le current_user est bien rattaché à l'offerer, mais simplement qu'il *existe* des users rattachés -> corrigé dans la branche 137
- on ne vérifie pas que le current_user a un user_offerer validé -> c'est à faire dans ce ticket

**Comment by abel-andre** [comment]
Non mais plutôt que de me casser la tête à split ça sur deux branches, je vais tout faire ici anyway.
