### ISSUE TITLE
[WEBAPP] Menu : Le menu ne se ferme pas si je clique sur la rubrique active.

### ISSUE THREAD

**Issue by IonLzr** [betagouv/pass-culture-browser#532]
Ex:  si j'ouvre le menu depuis _Mes réservations,_ et que je clique sur _Mes réservations,_ le menu reste ouvert.

**Comment by sixertoy** [comment]
Le click a été désactivé sur l'élément en cours
Je vais le réactiver et le rendre clickable pour fermer le menu

**Comment by IonLzr** [comment]
Cool, merci.

**Comment by sixertoy** [comment]
C'est noté thx, je m'en occupe
