### ISSUE TITLE
[WEBAPP] Le menu devrait scroller entièrement (pas seulement la liste des rubriques)

### ISSUE THREAD

**Issue by IonLzr** [betagouv/pass-culture-browser#533]

**Comment by sixertoy** [comment]
Y compris le header ?
Le menu doit avoir une hauteur fixe pour le moment
Car pour le moment il est fonctionnel en l'état et le refacto pour l'adapter en full responsive demanderait du temps qu'il vaudrait mettre à profit pour les autres enhancements graphiques
Donc on peut faire en sorte qu'il soit
- scrollable avec le header
- ou que tous les éléments soient scrollés (en dessous d'une hauteur max)

**Comment by IonLzr** [comment]
Oui, header compris. Le menu a été créé comme un badge (un pass…) et pour faire passer l'idée il faut (entre autres) qu'il scroll d'une seule pièce. En gros, c'est un seul grand bloc rouge. Et si ça dépasse l'écran, on fait défiler le bloc entier, comme un badge d'accès qui ne rentrerait pas à l'écran.

**Comment by sixertoy** [comment]
Noté je modifie, si ca prend pas trop de temps
Si je pense ce que c'est ca devrait le faire

**Comment by sixertoy** [comment]
En attente de le validation de la PR de la page profil pour livraison
