### ISSUE TITLE
[PRO][WEBAPP] Warning sur src/utils/string.js

### ISSUE THREAD

**Issue by annemarie35** [betagouv/pass-culture-browser#537]
Renvoie une erreur à corriger.

Commentaire @sixertoy :
On bouche cette ligne pour un warning eslint
Le problème dans les lignes suivantes c'est qu'on réassigne une variable existante
Ce qui en terme de bonne pratique est une erreur et peut provoquer des effets de bord à cause de l'assignation par référence de Javascript 

ici il faut créer une variable
```
let objectKey = null
const [key, value] = group.split('=') 
 switch (key) {
        case 'date':
          objectKey = '...'
          break;
```

ou alors, pour éviter de devoir remonter dans le code pour faire la liaison entre ce qui est retourner et ce qui est défini

```
switch (key) {
        case 'date':
          return Object.assign({}, result, { eventOccurrenceIdOrNew: value })
        case 'stock':
          return Object.assign({}, result, { stockIdOrNew: value })
        case 'lieu':
```

Même si il y a un truc qui me dérange car la structure de l'objet retourné est fluctuante du coup, le fait d'affecter une clé différente à l'objet
Ne peut-on pas avoir un type et une valeur plutôt ?
Car plus haut dans le code cela force à faire un switch ou un if non ?

**Comment by sixertoy** [comment]
fixed with commit 361924d
