### ISSUE TITLE
[PRO] Timezones fausses dans la saisie de date

### ISSUE THREAD

**Issue by arnoo** [betagouv/pass-culture-browser#544]
Prendre un événement de Guyanne, les eventOccurences sont affichées avec des dates en timezone Paris.

**Comment by g4vroche** [comment]
En fait on POST la date convertie en UTC par le client (donc la date est convertie depuis la TZ du poste utilisé pour saisir)

Il faudrait donc forcer la conversion en UTC depuis la TZ du lieu ?

Mon avis est qu'il vaux mieux le faire côté client (l'API reste plus simple, on post toujours en UTC / pas de magie)

A-t-on ce besoin à d'autres endroits ?

Qu'en pensez-vous ? @arnoo @Ledoux ?

**Comment by Ledoux** [comment]
tout à fait:

jusque là, on se débrouille toujours pour envoyer dans le requestData un
<machin>Datetime: <moment>Datetime.utc()

Et le display avec la tz...

normalement c'est ce component TimeInput qui devait justement nous macher le boulot, et il faisait son boulot, jusqu'à un certain moment
https://github.com/betagouv/pass-culture-shared/blob/master/src/components/forms/TimeInput.js#L9

Apparemment il fait plus son boulot. Et je crois que c'est lui qu'il faut aller voir.
