### ISSUE TITLE
[PRO] Il y a encore des structures sans leur lieu 'Offres en ligne'

### ISSUE THREAD

**Issue by Ledoux** [betagouv/pass-culture-browser#548]

**Comment by arnoo** [comment]
Nope : 
```
PROD => SELECT COUNT(*) FROM offerer o WHERE NOT EXISTS (SELECT 1 FROM venue v WHERE v."managingOffererId" = o.id);
 count 
-------
     0
```

Mais j'ai constaté la même chose : il y a du state qui reste dans l'app et n'est pas rafraîchi correctement.

**Comment by g4vroche** [comment]
Steps pour reproduire ?

**Comment by Ledoux** [comment]
J'avais vu ca pour la structure Ministere de la culture.

Mais là je revais sur staging et c'est bon.
