### ISSUE TITLE
[WEBAPP] icon erreur on signin page pas beau 

### ISSUE THREAD

**Issue by Ledoux** [betagouv/pass-culture-browser#555]

**Comment by IonLzr** [comment]
Sans doute la même chose, mais si ce n'est pas le cas : 
- rapprocher et rendre le message d'erreur solidaire du picto d'erreur, pour qu'ils s'affichent sur la même ligne et éviter la disposition illustrée sur la capture jointe. 
![signin-errors](https://user-images.githubusercontent.com/37805352/45363327-8512d480-b5d7-11e8-82a8-7ca7f66fb221.png)

**Comment by IonLzr** [comment]
Sans doute la même chose, mais si ce n'est pas le cas : 
- rapprocher et rendre le message d'erreur solidaire du picto d'erreur, pour qu'ils s'affichent sur la même ligne et éviter la disposition illustrée sur la capture jointe. 

![signin-errors](https://user-images.githubusercontent.com/37805352/45416970-610bcd80-b681-11e8-9df0-ba62df970fca.png)

**Comment by IonLzr** [comment]
Et ajouter une espace avant les ":" please (règle = tous les signes de ponctuation doubles sont précédés d'une espace : "?" ":" ";" "!").
