### ISSUE TITLE
[PRO] Bloquer l'édition sur l'écran de lieu si venue.isVirtual

### ISSUE THREAD

**Issue by arnoo** [betagouv/pass-culture-browser#562]

**Comment by g4vroche** [comment]
Pas sur de comprendre comment ça marche.

 * On créer automatiquement une venue avec `isVirtual = true` quand on créer une structure c'est ça ?
 * C'est ce lieu qu'il faut rendre non éditable ?

@arnoo ?

**Comment by Ledoux** [comment]
C'est fait ici en fait
https://github.com/betagouv/pass-culture-pro/pull/123/files#diff-018b35ee938292c2f3b8ed0b66e62ed2R144
