### ISSUE TITLE
[PRO] Affichage d'un lieu "Offre en ligne" pour chaque offreur dans "Lieux"

### ISSUE THREAD

**Issue by clemencechalopet** [betagouv/pass-culture-browser#564]

**Comment by arnoo** [comment]
C'est voulu. Tu trouves que ce n'est pas clair ?

**Comment by clemencechalopet** [comment]
je viens de comprendre, faut juste que je rajoute ça dans la brochure par
contre !

 * Clémence Chalopet*
  Chargée de* développement du Pass Culture | Seine-Saint-Denis et
opérateurs nationaux*
* <https://transport.beta.gouv.fr/>*  *3 rue de Valois, 75001 Paris
<https://fr.mappy.com/poi/53c8773ae4b05c124b45969e#/0/M2/TGeoentity/F53c8773ae4b05c124b45969e/N151.12061,6.11309,2.33756,48.86287/Z15/>
*
*  clemence.chalopet@beta.gouv.fr <clemence.chalopet@beta.gouv.fr>*

  +33 (0)6 46 78 81 35
   pass.culture.fr


2018-09-12 11:47 GMT+02:00 Arnaud Bétrémieux <notifications@github.com>:
