### ISSUE TITLE
[webapp] Affichage des dates en doublons dans le descriptif de l'offre

### ISSUE THREAD

**Issue by clemencechalopet** [betagouv/pass-culture-browser#566]

**Comment by arnoo** [comment]
Tu es sure que ce n'est pas la date qui est en doublon dans le portail PRO ?

**Comment by clemencechalopet** [comment]
non j'ai checké, il n'y a bien qu'une seule date dans le back office..

 * Clémence Chalopet*
  Chargée de* développement du Pass Culture | Seine-Saint-Denis et
opérateurs nationaux*
* <https://transport.beta.gouv.fr/>*  *3 rue de Valois, 75001 Paris
<https://fr.mappy.com/poi/53c8773ae4b05c124b45969e#/0/M2/TGeoentity/F53c8773ae4b05c124b45969e/N151.12061,6.11309,2.33756,48.86287/Z15/>
*
*  clemence.chalopet@beta.gouv.fr <clemence.chalopet@beta.gouv.fr>*

  +33 (0)6 46 78 81 35
   pass.culture.fr


2018-09-12 11:50 GMT+02:00 Arnaud Bétrémieux <notifications@github.com>:

**Comment by sixertoy** [comment]
Ola @clemencechalopet 
Je viens de checker les données sur cette offre
https://app.passculture.beta.gouv.fr/decouverte/AFVQ/AGCA

Le doublon vient des données, dans le jeu de données reçu les deux dates ont bien des IDs distincts
Peux tu faire une nouvelle passe sur PRO et nous confirmer
Thx :)

**Comment by clemencechalopet** [comment]
hello ! voilà ce que j'ai quand je vais sur l'offre :


 * Clémence Chalopet*
  Chargée de* développement du Pass Culture | Seine-Saint-Denis et
opérateurs nationaux*
* <https://transport.beta.gouv.fr/>*  *3 rue de Valois, 75001 Paris
<https://fr.mappy.com/poi/53c8773ae4b05c124b45969e#/0/M2/TGeoentity/F53c8773ae4b05c124b45969e/N151.12061,6.11309,2.33756,48.86287/Z15/>
*
*  clemence.chalopet@beta.gouv.fr <clemence.chalopet@beta.gouv.fr>*

  +33 (0)6 46 78 81 35
   pass.culture.fr

**Comment by ccompera** [comment]
Bonjour, j'ai le même problème sur plusieurs offres dont celle-ci :
https://app.passculture.beta.gouv.fr/decouverte/AKFQ/AK8A
<img width="432" alt="capture d ecran 2018-09-13 a 11 24 48" src="https://user-images.githubusercontent.com/9933870/45479832-d215b880-b747-11e8-864e-3cac6c23a3ac.png">
Or, sur PC pro : 
<img width="1088" alt="capture d ecran 2018-09-13 a 11 26 29" src="https://user-images.githubusercontent.com/9933870/45479858-e35ec500-b747-11e8-93bb-aff75bbe08ba.png">

**Comment by sixertoy** [comment]
A voir après le fix API/Pro

**Comment by ccompera** [comment]
Hello, 
Les horaires en double sont toujours existants. Cf mon dernier commentaire avec l'offre qui a plein d'horaires en double et mélangés.

Serait-il possible de faire une passe dans la BDD pour identifier tous les horaires en doublon et supprimer ceux qui n'ont pas de réservation ?

**Comment by arnoo** [comment]
Message pour les devs PRO : après analyse de la base il s'agit d'offres pour lesquelles on a 2 stocks pour chaque eventOccurence... je fais le ménage, et je vais voir si le problème existe encore.

**Comment by arnoo** [comment]
Nettoyage effectué. Vu les dates, le bug qui causait les doublons a bien été corrigé lorsqu'on a réparé le formulaire de dates / stocks → je ferme le ticket.
