### ISSUE TITLE
[PRO] Nombre de places reste nul pour une offre malgré modification

### ISSUE THREAD

**Issue by clemencechalopet** [betagouv/pass-culture-browser#568]
Beaucoup d'offres ne s'affichent pas dans l'app du coup..
![pj2_nbr_de_places](https://user-images.githubusercontent.com/37804697/45417416-64ec1f80-b682-11e8-9176-c9d9c9db5598.png)

![pj1_nbr_de_places](https://user-images.githubusercontent.com/37804697/45417354-42f29d00-b682-11e8-8ac0-1365cc36658c.png)
![pj3_nbr_de_place_vide](https://user-images.githubusercontent.com/37804697/45417359-45ed8d80-b682-11e8-8a28-da26d488fa63.png)
!

**Comment by arnoo** [comment]
Ce ne serait pas un doublon de ça ? https://github.com/betagouv/pass-culture-browser/issues/559

**Comment by clemencechalopet** [comment]
ah oui exact désolée...

 * Clémence Chalopet*
  Chargée de* développement du Pass Culture | Seine-Saint-Denis et
opérateurs nationaux*
* <https://transport.beta.gouv.fr/>*  *3 rue de Valois, 75001 Paris
<https://fr.mappy.com/poi/53c8773ae4b05c124b45969e#/0/M2/TGeoentity/F53c8773ae4b05c124b45969e/N151.12061,6.11309,2.33756,48.86287/Z15/>
*
*  clemence.chalopet@beta.gouv.fr <clemence.chalopet@beta.gouv.fr>*

  +33 (0)6 46 78 81 35
   pass.culture.fr


2018-09-12 11:52 GMT+02:00 Arnaud Bétrémieux <notifications@github.com>:
