### ISSUE TITLE
Faire une route [POST] [PATCH] /eventOccurrenceStocks

### ISSUE THREAD

**Issue by Ledoux** [betagouv/pass-culture-browser#583]
car ca sera plus facile pour faire le 

<img width="818" alt="screen shot 2018-09-14 at 15 39 46" src="https://user-images.githubusercontent.com/3239692/45559565-19cd3a80-b843-11e8-8d94-0c2ccd13d34c.png">

y aura juste cote frontend juste un seul <Form> un peu malin à gerer.
(au lieu d'en avoir un pour eventOccurrence plus un conditionnel pour stock)

**Comment by arnoo** [comment]
Finalement, c'est dommage et ça va coûter cher coté front. On va plutot faire la fusion stock / eventOccurence, mais plus tard (https://github.com/betagouv/pass-culture-browser/issues/622)
