### ISSUE TITLE
[API] Ajouter dans User :

### ISSUE THREAD

**Issue by sofcalca** [betagouv/pass-culture-browser#598]
- Nom (obligatoire)
- Prénom (obligatoire)
- Code postal (obligatoire)
- Numéro de téléphone (facultatif)

**Comment by sofcalca** [comment]
@arnoo @abel-andre il faudra penser à comment faire la migration. Ou on met ça en attente ?

**Comment by arnoo** [comment]
On prévoit une remise à zéro des utilisateurs, donc on peut mettre n'importe quoi pour les utilisateurs existants. 

sofcalca <notifications@github.com> writes:

> @arnoo @abel-andre il faudra penser à comment faire la migration. Ou on met ça en attente ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.


-- 
Arnaud Bétrémieux
Consultant
OCTO Technology
.....................
34, Avenue de l'Opéra
75002 Paris
+33 (0)6 89 85 88 41
du lundi au jeudi
http://www.octo.com/
http://blog.octo.com/
