### ISSUE TITLE
[WEBAPP] Brancher le bouton partage

### ISSUE THREAD

**Issue by arnoo** [betagouv/pass-culture-browser#601]
API navigator.share :

```
navigator
    .share({
        title: recommendation.offer.eventOrThing.name,
        text: 'demander le texte à Ion',
        url: <url de la reco>+&shared_by=<id_user>
    })
    .then(() => console.log('Successful share! 🎉'))
    .catch(err => console.error(err));

```
si !navigator.share pour l'instant, popup avec l'URL pour pouvoir la copier-coller

**Comment by sixertoy** [comment]
Tâche commencée sur la branche
https://github.com/betagouv/pass-culture-browser/tree/web_share

Reste à faire l'UI avec @IonLzr  et voir la fonctionnalité de partage à un ami

L'api navigator.share marche uniquement en HTTPS, j'ai donc pas testé depuis mon local
Mais ca devrait fonctionner

https://github.com/betagouv/pass-culture-browser/blob/web_share/src/components/layout/buttons/ShareButton.js#L22

**Comment by sixertoy** [comment]
Dans le RAF: il y a le quoi faire du shared_by ?

**Comment by IonLzr** [comment]
Comme vu ensemble, layouts ici (après clic sur btn partage) : https://octo.invisionapp.com/d/main#/console/13620708/285586245/preview#project_console
