### ISSUE TITLE
Faire un mini audit interne de sécu

### ISSUE THREAD

**Issue by arnoo** [betagouv/pass-culture-browser#605]
Couvrir les bases en attendant le vrai audit de sécurité : 
- [x] tout le monde a-t-il la 2FA activé sur scalingo et github ?
- [x] Tout le monde chiffre-t-il le disque sur son ordi ?
- [x] les routes ont-elles bien toutes une validation des droits et la bonne validation ?
- [x] s'est on protégé a peu près correctement contre le CORS et le CSRF dans webapp et pro ?

**Comment by g4vroche** [comment]
@DanielBaudry @annemarie35 @Ledoux vous pouvez vous dé-assigner si vous matchez les deux conditions : 

 * la 2FA activé sur scalingo et github
 * chiffrement du disque de son ordi

Si non faire le nécessaire / signaler les blocages éventuels (genre DD pas chiffré, ça doit pas être évident de "migrer")
