### ISSUE TITLE
[API] Ajouter champs IBAN et BIC sur offerer

### ISSUE THREAD

**Issue by arnoo** [betagouv/pass-culture-browser#618]
Avec validation:
- l'IBAN contient un clé de validation
- le BIC est à prendre dans une liste (ex https://www.juristique.org/droit/code-swift-code-bic)

Les champs sont optionnels, mais si l'un est la, l'autre doit l'être aussi.

**Comment by sofcalca** [comment]
Pour vérifier "l'IBAN contient un clé de validation" on vérifie la longueur ?

**Comment by arnoo** [comment]
Il ne s'agit pas de 'vérifier "l'IBAN contient un clé de validation"' mais de vérifier l'IBAN en utilisant la clé de validation inclue dedans :-)

sofcalca <notifications@github.com> writes:

> Pour vérifier "l'IBAN contient un clé de validation" on vérifie la longueur ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.


-- 
Arnaud Bétrémieux
Consultant
OCTO Technology
.....................
34, Avenue de l'Opéra
75002 Paris
+33 (0)6 89 85 88 41
du lundi au jeudi
http://www.octo.com/
http://blog.octo.com/

**Comment by sofcalca** [comment]
Tu parles de l'algorithme de vérification ici ? https://fr.wikipedia.org/wiki/International_Bank_Account_Number je n'ai pas trouvé d'infos sur une vérification avec la clef.
Et pour la liste de BIC, on va les chercher sur la page que tu as mise en lien ou on en crée une nous-mêmes ?

**Comment by arnoo** [comment]
Oui, c'est bien de cet algorithme qu'il s'agit. Il doit y avoir une lib python ?

Pour la liste de BIC, il s'agit d'en récupérer une quelque part qui ait l'air vaguement à jour et de la garder dans un coin. Je verrais bien un simple fichier json avec la liste en attendant mieux. A voir en fonction de la taille du dit fichier, mais il n'y a pas des milliards de banque, et il s'en crée relativement peu de nouvelles.

sofcalca <notifications@github.com> writes:

> Tu parles de l'algorithme de vérification ici ? https://fr.wikipedia.org/wiki/International_Bank_Account_Number je n'ai pas trouvé d'infos sur une vérification avec la clef.
> Et pour la liste de BIC, on va les chercher sur la page que tu as mise en lien ou on en crée une nous-mêmes ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.


-- 
Arnaud Bétrémieux
Consultant
OCTO Technology
.....................
34, Avenue de l'Opéra
75002 Paris
+33 (0)6 89 85 88 41
du lundi au jeudi
http://www.octo.com/
http://blog.octo.com/

**Comment by sofcalca** [comment]
une liste France uniquement ? Europe ?

**Comment by arnoo** [comment]
Je soupçonne que si tu as un siren tu as un compte en banque Français, mais je n'en suis pas sur. Si c'est le cas, on peut se contenter de la France pour l'instant.

sofcalca <notifications@github.com> writes:

> une liste France uniquement ? Europe ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.


-- 
Arnaud Bétrémieux
Consultant
OCTO Technology
.....................
34, Avenue de l'Opéra
75002 Paris
+33 (0)6 89 85 88 41
du lundi au jeudi
http://www.octo.com/
http://blog.octo.com/

**Comment by sofcalca** [comment]
ça te semble honnête comme source ? 
https://github.com/franckverrot/codes-bic-france/blob/master/codes-bic-france.csv 
Un seul contributeur mais ça ne m'a pas l'air délirant...
Je ne trouve aucune source officielle

**Comment by arnoo** [comment]
Yes, ça a l'air pas mal. Go avec ça, on améliorera au besoin. Pas de source officielle à ma connaissance.

sofcalca <notifications@github.com> writes:

> ça te semble honnête comme source ?
> https://github.com/franckverrot/codes-bic-france/blob/master/codes-bic-france.csv
> Un seul contributeur mais ça ne m'a pas l'air délirant...
> Je ne trouve aucune source officielle
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.


-- 
Arnaud Bétrémieux
Consultant
OCTO Technology
.....................
34, Avenue de l'Opéra
75002 Paris
+33 (0)6 89 85 88 41
du lundi au jeudi
http://www.octo.com/
http://blog.octo.com/
