### ISSUE TITLE
[PRO] Quand offreur crée offre une venueId lui est attribuée alors qu'il n'a pas de lieu

### ISSUE THREAD

**Issue by sofcalca** [betagouv/pass-culture-browser#626]
Pour reproduire : un offerer tout neuf qui n'a pas de lieu et essaye de faire une offre non numérique
ça poste avec un venueId qui semble être en fait l'offererId...

**Comment by g4vroche** [comment]
PR : https://github.com/betagouv/pass-culture-pro/pull/136
