### ISSUE TITLE
Faire la carte loading comme dans in vision

### ISSUE THREAD

**Issue by Ledoux** [betagouv/pass-culture-browser#64]

**Comment by augnustin** [comment]
On peut fermer, non ?

**Comment by Ledoux** [comment]
@augnustin 
En fait, @IonLzr est en train de finir le gif animé...
Donc une fois que c'est poussé sur un Invision, cette tache redevient pertinente

**Comment by IonLzr** [comment]
Le gif est dispo ici (les fichiers animés sont ± incompatibles avec inspect) : https://drive.google.com/open?id=1das9GNY6_53ChkVK3E6eaAf4TNi-YgCE
