### ISSUE TITLE
[API-PRO-WEBAPP] Est-ce que la route change password est si safe que ça?

### ISSUE THREAD

**Issue by Ledoux** [betagouv/pass-culture-browser#667]
suite à notre discussion 
@arnoo @abel-andre @g4vroche @sixertoy 

On utilise la app origin url:
https://github.com/betagouv/pass-culture-api/blob/master/routes/users.py#L78

c'est pas sensible au fishing ça?

**Comment by sixertoy** [comment]
la question existentielle du soir :D
ça fait titre d'émission de F. Tadei :D

**Comment by sixertoy** [comment]
ce commit ou jamais

**Comment by arnoo** [comment]
Qu'est ce qui te fait penser que ça pourrait l'être ? Tu peux donner un exemple de cas ? Je n'en vois pas comme ça.
ledoux <notifications@github.com> writes:

> suite à notre discussion
> @arnoo @abel-andre @g4vroche @sixertoy
>
> On utilise la app origin url:
> https://github.com/betagouv/pass-culture-api/blob/master/routes/users.py#L78
>
> c'est pas sensible au fishing ça?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.


-- 
Arnaud Bétrémieux
Consultant
OCTO Technology
.....................
34, Avenue de l'Opéra
75002 Paris
+33 (0)6 89 85 88 41
du lundi au jeudi
http://www.octo.com/
http://blog.octo.com/

**Comment by arnoo** [comment]
Ok compris en fait. Tu as raison. Par contre, il y a un ticket pour qu'on autorise que certaines origines (pour se prémunir contre le CSRF), qui va faire que ça ne sera plus possible.
