### ISSUE TITLE
Impossible d'entrer un horaire sous Safari

### ISSUE THREAD

**Issue by ccompera** [betagouv/pass-culture-browser#673]
Bonjour,

Lorsqu'on entre une heure dans une fiche offre sur Safari, cela fait n'importe quoi.
Exemple : je tape les chiffre 1 9 3 0 pour 19:30 et cela m'écris "05:10"...

J'utilise la version Version 12.0 (13606.2.11)

**Comment by Ledoux** [comment]
done here
https://github.com/betagouv/pass-culture-pro/pull/152
