### ISSUE TITLE
[PRO] Impossible de sélectionner le type "Musique (sur support physique ou en ligne)"

### ISSUE THREAD

**Issue by romaindel** [betagouv/pass-culture-browser#722]
Message de deezer : 
Bonjour Romain,

J'essaie de créer nos offres sur le portail pass culure (https://pro.passculture.beta.gouv.fr/offres/nouveau) et notre catégorie de produit ("Musique (sur support physique ou en ligne)") n'est pas sélectionnable.
Je suis toujours redirigé vers la catégorie "Musique (Concerts, festival)"

Pouvez vous me dire comment contourner le problème ?

Merci d'avance.

**Comment by Ledoux** [comment]
Done here https://github.com/betagouv/pass-culture-pro/pull/162
