### ISSUE TITLE
[PRO] Permettre de modifier les informations liées à une structure (adresse et désignation)

### ISSUE THREAD

**Issue by romaindel** [betagouv/pass-culture-browser#728]

**Comment by Ledoux** [comment]
On peut mais ca desynchronise la donnee avec celle de sirene.gouv et ca complexifie l ux du formulaire. (Pour le cas: j ai rempli avec un siren => ca a prerempli les adresses => je sauve. Je reviens plus tard, je commence a remodifier le siren => est ce que cette action doit maintenant reremplir l adresse ou non? )

L ideal serait qu il change directement a l urssaf!

**Comment by Ledoux** [comment]
Et donc du coup aujourdh'ui:

l'edition d'une structure n'a de sens que pour un admin qui souhaite modifier iban bic rib

**Comment by romaindel** [comment]
En effet, le ticket a été précisé dans [#889](https://github.com/betagouv/pass-culture-browser/issues/889) : on garde bien les informations sirene.gouv mais on permet juste d'éditer le nom affiché
