### ISSUE TITLE
[API] interdire de valider une contremarque qui ne m'appartient pas

### ISSUE THREAD

**Issue by romaindel** [betagouv/pass-culture-browser#732]
Pas moyen de tester si c'est un vrai bug de mon côté, mais si je tente de valider une contremarque (par ex la dernière reçue : Maelle Nedelec | maelle.nedelec29@gmail.com | BMLMWM pour Davodka / Swift Guad / Otomatik le 12 octobre 2018 à 20:30, proposé par CAC - Concarneau Scènes) dans mon compte PC pro, ça me donne bien la date de l'offre et l'info "Coupon vérifié, cliquez sur OK pour enregistrer".

Je précise que ce n'est pas un compte PC pro admin et que je n'ai pas essayé de valider la contremarque.

**Comment by g4vroche** [comment]
Je passe la patate chaude à la team API, les vérifications de sécurité sont effectuées de ce côté là.

**Comment by sofcalca** [comment]
Je prends le ticket

**Comment by sofcalca** [comment]
Pas de bug - on peut voir l'existence de la contremarque, mais lorsqu'on valide, on obtient un message d'erreur
