### ISSUE TITLE
[WEBAPP] Erreur d’icône une fois la réservation effectuée

### ISSUE THREAD

**Issue by arnoo** [betagouv/pass-culture-browser#748]
Le <Icon name=> dans VersoBookingButton semble incorrect

[EDIT][sofcalca] Il me semble que du coup un ne peut pas annuler les bookings côté jeune

**Comment by sixertoy** [comment]
comment dois faire l'user pour cancel son event ?
le bouton réservé c'est un toggle ?

**Comment by arnoo** [comment]
Je pensais qu'on l'avait déjà fait ', l'annulation ? je vais voir ou sont
les tickets et prioriser ca, mais pas tout de suite du coup.

Le lun. 8 oct. 2018 à 17:34, Matthieu Lassalvy <notifications@github.com> a
écrit :

**Comment by sixertoy** [comment]
Oki

**Comment by sixertoy** [comment]
Et pour celle ci pareil ?
https://github.com/betagouv/pass-culture-browser/issues/759

**Comment by arnoo** [comment]
Non, celle-ci c'est différent : si on annule une résa à la main (nous ou l'offreur, car ça c'est implémenté), il faut que l'utilisateur le voie d'une façon ou d'une autre sur le BookingItem et la fiche offre. Je ne sais pas si @IonLzr a prévu le coup.

Matthieu Lassalvy <notifications@github.com> writes:

> Et pour celle ci pareil ?
> #759
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.


-- 
Arnaud Bétrémieux
Consultant
OCTO Technology
.....................
34, Avenue de l'Opéra
75002 Paris
+33 (0)6 89 85 88 41
du lundi au jeudi
http://www.octo.com/
http://blog.octo.com/

**Comment by IonLzr** [comment]
C'était prévu sur la liste des résas : 
https://octo.invisionapp.com/d/main/#/console/13620708/287039464/preview#project_console

Sur la fiche Offre, l'idée est de décliner le style ci-dessus avec cette mise en place :
https://octo.invisionapp.com/d/main/#/console/13620708/285586244/preview#project_console

C'est bon pour vous ?

**Comment by IonLzr** [comment]
C'était prévu sur la liste des résas : 
https://octo.invisionapp.com/d/main/#/console/13620708/287039464/preview#project_console

Sur la fiche Offre, l'idée est de décliner le style ci-dessus avec la disposition suivante :
https://octo.invisionapp.com/d/main/#/console/13620708/285586244/preview#project_console

En plus, si on peut afficher au clic sur la bannière "annulé", une boîte disant :
> Cette réservation a été annulée [par [Nom de la structure]] [et/ou] [parce que [raison]]. Veuillez nous en excuser. // Fermer

… ce serait top.

Layout de l'alerte : 
https://octo.invisionapp.com/d/main/#/console/13620708/321629229/inspect

C'est bon pour vous ?

**Comment by IonLzr** [comment]
Sorry pour le doublon, le deuxième commentaire est le bon.
