### ISSUE TITLE
[WEBAPP] Certaines offres font planter l'appli

### ISSUE THREAD

**Issue by romaindel** [betagouv/pass-culture-browser#757]
Quelques exemples : https://app.passculture.beta.gouv.fr/decouverte/AMZQ/ALEA

https://app.passculture.beta.gouv.fr/decouverte/AMSQ/AK7A

https://app.passculture.beta.gouv.fr/decouverte/ANPA/AL3Q

**Comment by arnoo** [comment]
Il s'agit d'offres de type "objet" ayant plusieurs prix. Un des exemples est une offre qui est manifestement pour un évènement mais a été saisie comme offre avec plein de prix différents.

On avait déjà bloqué dans une livraison récente le fait de pouvoir mettre plusieurs prix pour simplifier pour les utilisateurs. J'ai fait le ménage dans la base lorsque c'était évident, il me reste trois offres ou je ne suis pas capable de savoir quel est le prix valide (on dirait que les utilisateurs ont plus joué avec l'appli que cherché à saisir une vraie offre). J'ai désactivé les offres correspondantes et je fais un mail aux utilisateurs.
