### ISSUE TITLE
[API] Ecart entre specs et dev sur l'API contremarque

### ISSUE THREAD

**Issue by romaindel** [betagouv/pass-culture-browser#801]
Re bonjour Romain,
 
Nous rencontrons un problème lors de nos tests avec l’environnement d’intégration de l’API PASS CULTURE en raison d’un écart entre les spécification et le comportement réel des services.
 
En effet, dans les spécifications, en cas d’erreur (retour 4xx) sur l’un des services GET ou POST /bookings/token/<token> il est indiqué que le payload de retour est un tableau au format suivant :
  [
    {
       "global": "<message>"
    }
  ]
 
 
Or dans les fait nous constatons que le retour de ces services en cas d’erreur (retour 4xx) est un json au format suivant :
{
    "global": [
        "<message"
    ]
}
 
Ce n’est pas la même chose car pas le même format d’objet à gérer en retour.
Peux-tu nous indiquer quelle est le format correct ? Et notamment celui qui sera utilisé en production ?
 
 
Cordialement,
__________________________________________________
Marion ARNAUD HAZEBROUCK
Tel: 01 71 35 16 14
Email: marion.arnaud@canal-plus.com
cid:image001.png@01CF1CF7.067AE190

**Comment by arnoo** [comment]
Déjà corrigé, cf mon mail d'hier :-)
