### ISSUE TITLE
[PRO] Procédure de validation lors de la création d'un lieu sans SIRET

### ISSUE THREAD

**Issue by romaindel** [betagouv/pass-culture-browser#804]
A designer le plus simplement possible : mail aux bizdev pour leur demander de prendre contact avec l'acteur, avec éventuellement ajout d'un champs texte sur l'interface pro pour que l'acteur puisse expliquer pourquoi il a besoin de créer un tel lieu

**Comment by arnoo** [comment]
Séparé en plusieurs tickets. Cependant, je soupçonne que ça fait trop pour cette itération coté API.
