### ISSUE TITLE
[WEBAPP] connexion automatique : un utilisateur connecté devrait accéder directement au caroussel

### ISSUE THREAD

**Issue by romaindel** [betagouv/pass-culture-browser#891]
L'URL https://app.passculture.beta.gouv.fr/ renvoie toujours vers https://app.passculture.beta.gouv.fr/beta (qui propose de se reconnecter).

Pour les utilisateurs déjà connectés, il faudrait renvoyer vers https://app.passculture.beta.gouv.fr/decouverte pour accéder directement au caroussel

**Comment by sixertoy** [comment]
@Ledoux tu pourras jeter un oeil au commit please
En regardant shared, je me dis trois choses
- on peut faire de withLogin un wrapper qui pourrait directement être sur la fabrication des routes
- le push dans le redirect du login pourrait être un replace (force de l'history back)
- la diff entre NoPage/NotMatch Webapp/Shared peut être mutualisé dans shared 🎉
Thoughts ?
