### ISSUE TITLE
[API] [PRO] Quand une structure existe déjà, un nouvel utilisateur rattaché ne peut pas créer des offres

### ISSUE THREAD

**Issue by sofcalca** [betagouv/pass-culture-browser#906]

**Comment by g4vroche** [comment]
@sofcalca peux tu préciser le(s) problème(s) actuels ?
Vu le titre je suppose qu'il y a des choses à faire côté API comme PRO ?

**Comment by sofcalca** [comment]
En fait en relisant l'issue, il me semble que c'est juste parce que l'user_offerer n'est pas validé (et que donc c'est normal). 
Je ferme.
