### ISSUE TITLE
S'assurer que le bouton retour marche partout

### ISSUE THREAD

**Issue by Ledoux** [betagouv/pass-culture-browser#92]

**Comment by augnustin** [comment]
Désormais lorsqu'une modale est ouverte et le bouton back pressé, cela ferme la modale. Pour le reste de l'app, le bouton back fait un "retour" du navigateur. A priori c'est le comportement attendu.

Je ferme donc, mais n'hésitez pas à rouvrir (ou à créer une autre issue) s'il y a d'autres cas où ça ne se passe pas comme prévu.
